// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import WorkoutTemplateConcept from "./WorkoutTemplate/WorkoutTemplateConcept.ts";
import WorkoutLogConcept from "./WorkoutLog/WorkoutLogConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import ProgressionGuidanceConcept from "./ProgressionGuidance/ProgressionGuidanceConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";
import ExerciseLibraryConcept from "./ExerciseLibrary/ExerciseLibraryConcept.ts";

export type { default as WorkoutTemplateConcept } from "./WorkoutTemplate/WorkoutTemplateConcept.ts";
export type { default as WorkoutLogConcept } from "./WorkoutLog/WorkoutLogConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as ProgressionGuidanceConcept } from "./ProgressionGuidance/ProgressionGuidanceConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";
export type { default as ExerciseLibraryConcept } from "./ExerciseLibrary/ExerciseLibraryConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const WorkoutTemplate = Engine.instrumentConcept(new WorkoutTemplateConcept(db));
export const WorkoutLog = Engine.instrumentConcept(new WorkoutLogConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const ProgressionGuidance = Engine.instrumentConcept(new ProgressionGuidanceConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
export const ExerciseLibrary = Engine.instrumentConcept(new ExerciseLibraryConcept(db));
